/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import Entidades.Calculadora;
import Logica.LogicaCalculadora;
import Servicios.ServicioCalculadora;
import javax.swing.JOptionPane;

/**
 *
 * @author Empresaurio50
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    private Calculadora objCalculadora = new Calculadora();
    private final ServicioCalculadora servicioCalculadora = new LogicaCalculadora();

    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVista = new javax.swing.JLabel();
        btt0 = new javax.swing.JButton();
        bttMultiplicar = new javax.swing.JButton();
        bttDivision = new javax.swing.JButton();
        btt9 = new javax.swing.JButton();
        btt8 = new javax.swing.JButton();
        btt6 = new javax.swing.JButton();
        bttSuma = new javax.swing.JButton();
        btt7 = new javax.swing.JButton();
        bttResta = new javax.swing.JButton();
        btt1 = new javax.swing.JButton();
        btt4 = new javax.swing.JButton();
        btt3 = new javax.swing.JButton();
        btt5 = new javax.swing.JButton();
        btt2 = new javax.swing.JButton();
        bttResultado = new javax.swing.JButton();
        bttLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(146, 49, 82));

        lblVista.setBackground(new java.awt.Color(255, 255, 255));
        lblVista.setForeground(new java.awt.Color(0, 0, 0));
        lblVista.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblVista.setOpaque(true);

        btt0.setBackground(new java.awt.Color(204, 204, 204));
        btt0.setText("0");
        btt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt0ActionPerformed(evt);
            }
        });

        bttMultiplicar.setBackground(new java.awt.Color(204, 204, 204));
        bttMultiplicar.setText("*");
        bttMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMultiplicarActionPerformed(evt);
            }
        });

        bttDivision.setBackground(new java.awt.Color(204, 204, 204));
        bttDivision.setText("/");
        bttDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDivisionActionPerformed(evt);
            }
        });

        btt9.setBackground(new java.awt.Color(204, 204, 204));
        btt9.setText("9");
        btt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt9ActionPerformed(evt);
            }
        });

        btt8.setBackground(new java.awt.Color(204, 204, 204));
        btt8.setText("8");
        btt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt8ActionPerformed(evt);
            }
        });

        btt6.setBackground(new java.awt.Color(204, 204, 204));
        btt6.setText("6");
        btt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt6ActionPerformed(evt);
            }
        });

        bttSuma.setBackground(new java.awt.Color(204, 204, 204));
        bttSuma.setText("+");
        bttSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSumaActionPerformed(evt);
            }
        });

        btt7.setBackground(new java.awt.Color(204, 204, 204));
        btt7.setText("7");
        btt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt7ActionPerformed(evt);
            }
        });

        bttResta.setBackground(new java.awt.Color(204, 204, 204));
        bttResta.setText("-");
        bttResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRestaActionPerformed(evt);
            }
        });

        btt1.setBackground(new java.awt.Color(204, 204, 204));
        btt1.setText("1");
        btt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt1ActionPerformed(evt);
            }
        });

        btt4.setBackground(new java.awt.Color(204, 204, 204));
        btt4.setText("4");
        btt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt4ActionPerformed(evt);
            }
        });

        btt3.setBackground(new java.awt.Color(204, 204, 204));
        btt3.setText("3");
        btt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt3ActionPerformed(evt);
            }
        });

        btt5.setBackground(new java.awt.Color(204, 204, 204));
        btt5.setText("5");
        btt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt5ActionPerformed(evt);
            }
        });

        btt2.setBackground(new java.awt.Color(204, 204, 204));
        btt2.setText("2");
        btt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt2ActionPerformed(evt);
            }
        });

        bttResultado.setBackground(new java.awt.Color(204, 204, 204));
        bttResultado.setText("=");
        bttResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttResultadoActionPerformed(evt);
            }
        });

        bttLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        bttLimpiar.setText("C");
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btt4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btt5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btt6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bttResta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btt7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btt8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btt9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bttMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bttResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btt1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btt2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btt3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bttSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bttLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btt0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bttDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttResta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt1ActionPerformed
        this.lblVista.setText(lblVista.getText() + "1");
    }//GEN-LAST:event_btt1ActionPerformed

    private void bttSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSumaActionPerformed
        
        objCalculadora = new Calculadora();
        
        
        objCalculadora.setNumero1(Integer.parseInt(lblVista.getText()));
        
        objCalculadora.setOperador("+");
        
        this.lblVista.setText("");
    }//GEN-LAST:event_bttSumaActionPerformed

    private void btt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt2ActionPerformed
        this.lblVista.setText(lblVista.getText() + "2");
    }//GEN-LAST:event_btt2ActionPerformed

    private void btt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt3ActionPerformed
        this.lblVista.setText(lblVista.getText() + "3");
    }//GEN-LAST:event_btt3ActionPerformed

    private void btt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt4ActionPerformed
        this.lblVista.setText(lblVista.getText() + "4");
    }//GEN-LAST:event_btt4ActionPerformed

    private void btt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt5ActionPerformed
        this.lblVista.setText(lblVista.getText() + "5");
    }//GEN-LAST:event_btt5ActionPerformed

    private void btt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt6ActionPerformed
        this.lblVista.setText(lblVista.getText() + "6");
    }//GEN-LAST:event_btt6ActionPerformed

    private void btt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt7ActionPerformed
        this.lblVista.setText(lblVista.getText() + "7");
    }//GEN-LAST:event_btt7ActionPerformed

    private void btt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt8ActionPerformed
        this.lblVista.setText(lblVista.getText() + "8");
    }//GEN-LAST:event_btt8ActionPerformed

    private void btt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt9ActionPerformed
        this.lblVista.setText(lblVista.getText() + "9");
    }//GEN-LAST:event_btt9ActionPerformed

    private void btt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt0ActionPerformed
        this.lblVista.setText(lblVista.getText() + "0");
    }//GEN-LAST:event_btt0ActionPerformed

    private void bttDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDivisionActionPerformed
        this.lblVista.setText(lblVista.getText() + "/");
    }//GEN-LAST:event_bttDivisionActionPerformed

    private void bttRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRestaActionPerformed
        this.lblVista.setText(lblVista.getText() + "-");
    }//GEN-LAST:event_bttRestaActionPerformed

    private void bttMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMultiplicarActionPerformed
        this.lblVista.setText(lblVista.getText() + "*");
    }//GEN-LAST:event_bttMultiplicarActionPerformed

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        
        this.lblVista.setText("");
    }//GEN-LAST:event_bttLimpiarActionPerformed

    private void bttResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttResultadoActionPerformed
        
        objCalculadora.setNumero2(Integer.parseInt(lblVista.getText()));
        
        try {
            servicioCalculadora.operadores(objCalculadora);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        lblVista.setText(String.valueOf(objCalculadora.getResultado()));
        
    }//GEN-LAST:event_bttResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt0;
    private javax.swing.JButton btt1;
    private javax.swing.JButton btt2;
    private javax.swing.JButton btt3;
    private javax.swing.JButton btt4;
    private javax.swing.JButton btt5;
    private javax.swing.JButton btt6;
    private javax.swing.JButton btt7;
    private javax.swing.JButton btt8;
    private javax.swing.JButton btt9;
    private javax.swing.JButton bttDivision;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttMultiplicar;
    private javax.swing.JButton bttResta;
    private javax.swing.JButton bttResultado;
    private javax.swing.JButton bttSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblVista;
    // End of variables declaration//GEN-END:variables
}
