/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import Entidades.Calculadora;
import CustomExcepcion.ExcepcionesPersonalizadas;
import Logica.LogicaCalculadora;
import javax.swing.JOptionPane;
import Servicios.ServicioCalculadora;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Empresaurio50
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Calculadora objCalculadora = new Calculadora();
    ServicioCalculadora servicioCalculadora = new LogicaCalculadora();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        servicioCalculadora = new LogicaCalculadora();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNumero1 = new javax.swing.JLabel();
        lblNumero2 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        bttSumar = new javax.swing.JButton();
        bttMultiplicar = new javax.swing.JButton();
        bttResta = new javax.swing.JButton();
        bttDividir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblTitulo.setText("Calculadora");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        lblNumero1.setText("Numero 1");
        jPanel1.add(lblNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblNumero2.setText("Numero 2");
        jPanel1.add(lblNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, 30));
        jPanel1.add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 130, 30));

        bttSumar.setText("Suma");
        bttSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSumarActionPerformed(evt);
            }
        });
        jPanel1.add(bttSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        bttMultiplicar.setText("Multiplicar");
        bttMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(bttMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        bttResta.setText("Resta");
        bttResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRestaActionPerformed(evt);
            }
        });
        jPanel1.add(bttResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        bttDividir.setText("Dividir");
        bttDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDividirActionPerformed(evt);
            }
        });
        jPanel1.add(bttDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jScrollPane1.setViewportView(txtResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, -1));

        jScrollPane2.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void capturarDatos(Calculadora objCalculadora) throws ExcepcionesPersonalizadas{
        
        if (txtNumero1.getText().equals(null) || txtNumero2.getText().equals(null)) {
            
            throw new ExcepcionesPersonalizadas("Las casillas estan vacias");
            
        }
        
        objCalculadora.setNumero1(Integer.parseInt( txtNumero1.getText()));
        
        objCalculadora.setNumero2(Integer.parseInt(txtNumero2.getText()));
        
        
        
    }
    
    
    private void bttSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSumarActionPerformed
        
        try {
            capturarDatos(objCalculadora);
            
            servicioCalculadora.sumar(objCalculadora);
            
            txtResultado.setText((String.valueOf((objCalculadora.getResultado()))));
        } catch (ExcepcionesPersonalizadas e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bttSumarActionPerformed

    private void bttMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMultiplicarActionPerformed
        
        try {
            capturarDatos(objCalculadora);
            
            servicioCalculadora.multiplicar(objCalculadora);
            
            txtResultado.setText(String.valueOf(objCalculadora.getResultado()));
            
        } catch (ExcepcionesPersonalizadas ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_bttMultiplicarActionPerformed

    private void bttRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRestaActionPerformed
        
        try {
            
            capturarDatos(objCalculadora);
            
            servicioCalculadora.resta(objCalculadora);
            
            txtResultado.setText(String.valueOf(objCalculadora.getResultado()));
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_bttRestaActionPerformed

    private void bttDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDividirActionPerformed
        
        try {
            
            capturarDatos(objCalculadora);
            
            servicioCalculadora.dividir(objCalculadora);
            
            txtResultado.setText(String.valueOf(objCalculadora.getResultado()));
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_bttDividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttDividir;
    private javax.swing.JButton bttMultiplicar;
    private javax.swing.JButton bttResta;
    private javax.swing.JButton bttSumar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextPane txtResultado;
    // End of variables declaration//GEN-END:variables
}
